apiVersion: v1
appVersion: v0.0.1-rc10
description: Backup-restore-operator can be used to backup kubernetes cluster metadata
  for certain applications and restore from it
name: backup-restore-operator
keywords:
- applications
- infrastructure
version: 0.0.1
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-resources-system
  catalog.cattle.io/release-name: backup-restore-operator
  catalog.cattle.io/ui-component: backup-restore-operator
  catalog.cattle.io/provides-gvr: resources.cattle.io.resourceset/v1
