url: https://github.com/prometheus-community/helm-charts.git
subdirectory: charts/kube-prometheus-stack
commit: 3ca6ba66032a1efce0500f9ad6f83351ad0604b8
packageVersion: 02
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: crd-manifest
      addCRDValidationToMainChart: true
