apiVersion: v1
name: rio
version: 0.8.1
appVersion: 0.8.0
description: The application deployment engine for Kubernetes
home: https://rio.io
icon: https://charts.rancher.io/assets/logos/rio.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: rio-system
  catalog.cattle.io/release-name: rio
  catalog.cattle.io/hidden: true
  catalog.cattle.io/experimental: true
  catalog.cattle.io/requires-gvr: networking.istio.io.virtualservice/v1beta1
  catalog.cattle.io/display-name: "Rio"
