apiVersion: v1
name: rio
version: 0.8.000
appVersion: 0.8.0-rc2
description: The application deployment engine for Kubernetes
home: https://rio.io
icon: https://charts.rancher.io/assets/logos/rio.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: rio-system
  catalog.cattle.io/release-name: rio
  catalog.cattle.io/experimental: true