{{- if not .Values.cert_manager -}}
{{- if .Values.webhook.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: operator-webhook-service
  namespace: {{ .Release.Namespace }}
data:
{{ include "sriov_operator_cert" . | indent 2 }}
{{- end }}
---
{{- if .Values.injector.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: network-resources-injector-secret
  namespace: {{ .Release.Namespace }}
data:
{{ include "sriov_resource_injector_cert" . | indent 2 }}
{{- end }}
{{- end }}
