annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-system
  catalog.cattle.io/os: linux
  catalog.cattle.io/release-name: rancher-webhook
apiVersion: v2
appVersion: 0.2.0-alpha
dependencies:
- condition: capi.enabled
  name: capi
  repository: ""
description: ValidatingAdmissionWebhook for Rancher types
name: rancher-webhook
version: 0.2.1-alpha+up0.2.0-alpha01
