url: https://github.com/open-policy-agent/gatekeeper.git
subdirectory: charts/gatekeeper
type: git
commit: 58ae7eacd2f93831b55557d0cd56ffdc3e04ab9a
generateCRDChart:
  enabled: true
  providesGVR: configs.config.gatekeeper.sh/v1alpha1
