operator:
  image:
    repository: rancher/hardened-sriov-network-operator
    tag: v1.0.0-build20210429

cni:
  image:
    repository: rancher/hardened-sriov-cni
    tag: v2.6-build20210310

cni_infiniband:
  image:
    repository: rancher/hardened-ib-sriov-cni
    tag: v1.0.0-build20210310

device_plugin:
  image:
    repository: rancher/hardened-sriov-network-device-plugin
    tag: v3.3.1-build20210310

injector:
  image:
    repository: rancher/hardened-sriov-network-resources-injector
    tag: v1-build20210310
  enable: false

config_daemon:
  image:
    repository: rancher/hardened-sriov-network-config-daemon
    tag: v1.0.0-build20210429

webhook:
  image:
    repository: rancher/hardened-sriov-network-webhook
    tag: v1.0.0-build20210429
  enable: false

# cert_manager enables integration with cert-manager to generate
# certificates for the operator webhooks. Otherwise the chart will
# generate ad-hoc certificates with no automated renewal at expiration,
# not recommended for production clusters.
cert_manager: true

global:
  cattle:
    systemDefaultRegistry: ""
