# Default values for rancher-alerting-driver.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  cattle:
    # the registry where all images will be pulled from
    systemDefaultRegistry: ""
  kubectl:
    repository: rancher/kubectl
    tag: v1.20.2

prom2teams:
  enabled: false

sachet:
  enabled: false
