apiVersion: batch/v1
kind: Job
metadata:
  name: istioctl-installer
  namespace: {{ template "istio.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 1
  template:
    spec:
      containers:
        - name: istioctl-installer
          image: {{ template "system_default_registry" . }}{{ .Values.installer.repository }}:{{ .Values.installer.tag }}
          imagePullPolicy: '{{ .Values.installer.pullPolicy }}'
          env:
          - name: RELEASE_NAME
            value: {{ .Release.Name }}
          - name: ISTIO_NAMESPACE
            value: {{ template "istio.namespace" . }}
          - name: FORCE_INSTALL
            value: {{ .Values.forceInstall | default "false" | quote }}
          command: ["/bin/sh","-c"]
          args: ["/usr/local/app/scripts/run.sh"]
          volumeMounts:
          - name: config-volume
            mountPath: /app/istio-base.yaml
            subPath: istio-base.yaml
          {{- if .Values.overlayFile }}
          - name: overlay-volume
            mountPath: /app/overlay-config.yaml
            subPath: overlay-config.yaml
          {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: istio-installer-base
        {{- if .Values.overlayFile }}
        - name: overlay-volume
          configMap:
            name: istio-installer-overlay
        {{- end }}
      imagePullSecrets:
{{ toYaml .Values.installer.pullSecrets | indent 8 }}
      serviceAccountName: istio-installer
      {{- if .Values.global.rbac.pspEnabled }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
      {{- end }}
      restartPolicy: Never
