name: neuvector
apiVersion: v1
version: 1.3.4
appVersion: 2.5.0
description: NeuVector Full LifeCycle Container Security Platform delivers the only cloud-native Kubernetes security platform with uncompromising end-to-end protection from DevOps vulnerability protection to automated run-time security, and featuring a true Layer 7 container firewall.
home: https://neuvector.com
maintainers:
  - name: Sun
    email: xfsun@neuvector.com
engine: gotpl
