apiVersion: v2
appVersion: 1.99.99-dev-app
description: Instana Agent for Kubernetes
home: https://www.instana.com/
icon: file://../stan-logo-2020.png
maintainers:
- email: henning.treu@ibm.com
  name: htreu
- email: jon.brisbin@instana.com
  name: jbrisbin
- email: william.james@instana.com
  name: wiggzz
- email: jeroen.soeters@instana.com
  name: JeroenSoeters
- email: fabian.staeber@instana.com
  name: fstab
- email: miel.donkers@instana.com
  name: mdonkers
- email: dahlia.bock@instana.com
  name: dlbock
- email: nathan.fisher@instana.com
  name: nfisher
name: instana-agent
sources:
- https://github.com/instana/instana-agent-docker
version: 1.2.13
