apiVersion: v1
appVersion: v0.0.1
description: The cis-operator enables running CIS benchmark security scans on a kubernetes
  cluster
name: rancher-cis-benchmark
version: 0.0.1
keywords:
- security
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cis-operator-system
  catalog.cattle.io/release-name: rancher-cis-benchmark
  catalog.cattle.io/ui-component: rancher-cis-benchmark
  catalog.cattle.io/provides-gvr: cis.cattle.io.clusterscans/v1
