apiVersion: v1
appVersion: 1.6.7
description: Helm chart for installing istio components with the istioctl
name: rancher-istio-installer
version: 1.6.700
icon: https://charts.rancher.io/assets/logos/istio.svg
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: istio-system
  catalog.cattle.io/release-name: rancher-istio
  catalog.cattle.io/ui-component: istio
  catalog.cattle.io/requires-gvr: prometheuses.monitoring.coreos.com/v1
  catalog.cattle.io/auto-install-gvr: monitoringdashboards.monitoring.kiali.io/v1alpha1
