revision: "" # leave blank for no canary deployment, or set to given revision, eg: "1-7-2"
overlayFile: ""
tag: 1.6.8
installerVersion: 0.1.6
forceInstall: false

istiocoredns:
    enabled: false
    image:
      repository: rancher/coredns-coredns
      tag: 1.6.2
    pluginImage:
      repository: rancher/istio-coredns-plugin
      tag: 0.2-istio-1.1

base:
    enabled: true

cni:
    enabled: false
    repository: rancher/istio-install-cni
    tag: 1.6.8

egressGateways:
    enabled: false
    type: NodePort

ingressGateways:
    enabled: true
    type: NodePort

istiodRemote:
    enabled: false

pilot:
    enabled: true
    repository: rancher/istio-pilot
    tag: 1.6.8

policy:
    enabled: true
    repository: rancher/istio-mixer
    tag: 1.6.8

telemetry:
    enabled: true
    repository: rancher/istio-mixer
    tag: 1.6.8

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  objectSelector:
    enabled: true
    autoInject: true
  rewriteAppHTTPProbe: true

global:
  systemDefaultRegistry: ""
  proxy:
    repository: rancher/istio-proxyv2
    tag: 1.6.8
  proxy_init:
    repository: rancher/istio-proxyv2
    tag: 1.6.8

# this can be removed in 1.7 as it is default
meshConfig:
  enablePrometheusMerge: true

# Kiali subchart from rancher-kiali-server
kiali:
  enabled: true
  auth:
    strategy: anonymous
  deployment:
    ##TODO: update kiali to allow for repository and image
    ingress_enabled: false
    image_name: docker.io/rancher/kiali-kiali
    image_version: v1.22.1
  external_services:
    prometheus:
      custom_metrics_url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
      url: "http://rancher-monitoring-prometheus.cattle-monitoring-system.svc:9090"
    tracing:
      enabled: false
