revision: "" # leave blank for no canary deployment, or set to given revision, eg: "1-7-2"
overlayFile: ""
tag: 1.6.7
installerVersion: 0.1.5

istiocoredns:
    enabled: false
    image:
      repository: coredns/coredns
      tag: 1.6.2
    pluginImage: istio/coredns-plugin:0.2-istio-1.1

base:
    enabled: true

cni:
    enabled: false

egressGateways:
    enabled: false
    type: NodePort

ingressGateways:
    enabled: true
    type: NodePort

istiodRemote:
    enabled: false

pilot:
    enabled: true
    image: pilot

policy:
    enabled: true
    image: mixer

telemetry:
    enabled: true
    image: mixer

sidecarInjectorWebhook:
  enableNamespacesByDefault: false
  objectSelector:
    enabled: true
    autoInject: true
  rewriteAppHTTPProbe: true

global:
  proxy:
    image: proxyv2
  proxy_init:
    image: proxyv2

# this can be removed in 1.7 as it is default
meshConfig:
  enablePrometheusMerge: true

# Kiali subchart from rancher-kiali-server
kiali:
  enabled: true
  auth:
    # todo: what auth strategy ?
    # strategy: token # this is default, you can use a service-account or kubeconfig token
    strategy: anonymous
  deployment:
    ingress_enabled: false
  external_services:
    prometheus:
      custom_metrics_url: "http://monitoring-rancher-monitor-prometheus.monitoring-system.svc:9090"
      url: "http://monitoring-rancher-monitor-prometheus.monitoring-system.svc:9090"
    tracing:
      enabled: false
  # TODO : update images
  # deployment:
  #   image_name: "rancher..."
  #   image_version: v1.....
