{{- if .Values.createCustomResource }}
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "cert-manager.fullname" . }}-crd
data:
  crds.yaml: |-
{{.Files.Get "files/crds.yaml" | printf "%s" | indent 4}}
{{- end }}
