annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/namespace: cattle-resources-system
  catalog.cattle.io/release-name: rancher-backup-crd
apiVersion: v2
appVersion: 1.0.5-rc1
description: Installs the CRDs for rancher-backup.
name: rancher-backup-crd
type: application
version: 1.0.500-rc1+up1.0.5-rc1
