apiVersion: v1
version: 1.0.6
description: Installs the CRDs for rancher-cis-benchmark.
name: rancher-cis-benchmark-crd
type: application
annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: rancher-cis-benchmark-crd
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cis-operator-system
