url: https://kiali.org/helm-charts/kiali-server-1.29.0.tgz
packageVersion: 01
releaseCandidateVersion: 00
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
