apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  #namespace: {{ .Values.stackNamespace}}
  labels:
    app: app-shuttle
spec:
  ports:
    - port: 5432
      name: postgres-port
  selector:
    app: app-shuttle
  clusterIP: None
