apiVersion: v1
version: 3.1.1
description: Installs the CRDs for rancher-gatekeeper.
name: rancher-gatekeeper-crd
type: application
annotations:
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/release-name: rancher-gatekeeper-crd
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/experimental: true
  catalog.cattle.io/namespace: cattle-gatekeeper-system
