{{- if .Values.additionalLoggingSources.rke2.enabled }}
apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ .Release.Name }}-rke2-journald
  namespace: {{ .Release.Namespace }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentbit:
    image:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.fluentbit.repository }}
      tag: {{ .Values.images.fluentbit.tag }}
    inputTail:
      Tag: "rke2"
      Path: "/etc/rancher/logging/logs/*.log"
    extraVolumeMounts:
      - source: "/etc/rancher/logging/logs/"
        destination: "/etc/rancher/logging/logs/"
        readOnly: true
    {{- if .Values.global.psp.enabled }}
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    {{- end }}
  {{- $total_tolerations := concat (.Values.tolerations) (.Values.fluentbit.tolerations) }}
  {{- with $total_tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.fluentbit.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
  {{- end }}
  fluentd:
    image:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.fluentd.repository }}
      tag: {{ .Values.images.fluentd.tag }}
    configReloaderImage:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.config_reloader.repository }}
      tag: {{ .Values.images.config_reloader.tag }}
    disablePvc: {{ .Values.disablePvc }}
    {{- if .Values.global.psp.enabled }}
    security:
      podSecurityPolicyCreate: true
      roleBasedAccessControlCreate: true
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.fluentd.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
