# Default values for cpx-istio.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

istioAdaptor:
    image: quay.io/citrix/citrix-istio-adaptor
    tag: 1.2.0
    imagePullPolicy: IfNotPresent
    netscalerUrl: "http://127.0.0.1"
    proxyType: sidecar
    secureConnect: true
    ADMIP:
    ADMFingerPrint:
    coeURL:
 
istioPilot:
    name: istio-pilot
    namespace: istio-system
    secureGrpcPort: 15011
    insecureGrpcPort: 15010
    SAN: "spiffe://cluster.local/ns/istio-system/sa/istio-pilot-service-account"

cpxProxy:
    image: quay.io/citrix/citrix-k8s-cpx-ingress
    tag: 13.0-47.22
    imagePullPolicy: IfNotPresent
    EULA: NO
    cpxSidecarMode: YES
    mgmtHttpPort: 10080
    mgmtHttpsPort: 10443
    # licenseServerIP: this value is taken from istio.Adaptor.ADMIP
    licenseServerPort: 27000

sidecarWebHook:
    webhookImage: gcr.io/istio-release/sidecar_injector
    webhookImageVersion: 1.0.0
    imagePullPolicy: IfNotPresent

webhook:
    injectionLabelName: cpx-injection
