apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-e-2-e-scheduling-latency-seconds-quantile
spec:
  enable: true
  resourceType: scheduler
  priority: 320
  title: scheduler-e-2-e-scheduling-latency-seconds-quantile
  thresholds: 10
  metricsSelector:
    details: "false"
    component: scheduler
    metric: e-2-e-scheduling-latency-seconds-quantile
  detailsMetricsSelector:
    details: "true"
    component: scheduler
    metric: e-2-e-scheduling-latency-seconds-quantile
  yAxis:
    unit: seconds
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-total-preemption-attempts
spec:
  enable: true
  resourceType: scheduler
  priority: 321
  title: scheduler-total-preemption-attempts
  thresholds: 10
  metricsSelector:
    details: "false"
    component: scheduler
    metric: total-preemption-attempts
  detailsMetricsSelector:
    details: "true"
    component: scheduler
    metric: total-preemption-attempts
  yAxis:
    unit: number
---
apiVersion: management.cattle.io/v3
kind: ClusterMonitorGraph
metadata:
  labels:
    app: metric-expression
    source: rancher-monitoring
    level: cluster
    component: scheduler
    cluster-graph: kube-component
  name: scheduler-pod-unscheduler
spec:
  enable: true
  resourceType: scheduler
  priority: 322
  title: scheduler-pod-unscheduler
  thresholds: 10
  metricsSelector:
    details: "false"
    component: scheduler
    metric: pod-unscheduler
  detailsMetricsSelector:
    details: "true"
    component: scheduler
    metric: pod-unscheduler
  yAxis:
    unit: number