{{- if not (typeIs "[]interface {}" .Values.agent.image.pullSecrets) }}
{{- if .Values.agent.image.name | hasPrefix "containers.instana.io" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: containers-instana-io
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instana-agent.commonLabels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretContainersInstanaIo" . }}
{{- end -}}
{{- end -}}
{{- if not .Values.agent.keysSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "instana-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "instana-agent.commonLabels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.templating }}
  key: {{ .Values.agent.key }}
  downloadKey: {{ default "" .Values.agent.downloadKey }}
{{- else }}
{{- if .Values.agent.key }}
  key: {{ .Values.agent.key | b64enc | quote }}
{{- end }}
{{- if .Values.agent.downloadKey }}
  downloadKey: {{ .Values.agent.downloadKey | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
