{{- if .Values.rbacEnable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "spark.fullname" . }}
  labels:
    app: {{ template "spark.name" . }}
    chart: {{ template "spark.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  namespace: {{ .Release.Namespace }}
{{- end }}
