apiVersion: v1
appVersion: 0.9.0
description: A Helm chart for Knative
name: knative
icon: file://../logo.svg
home: https://github.com/knative
sources:
  - https://gitlab.com/gitlab-org/charts/knative
  - https://github.com/triggermesh/charts
version: 0.9.0
maintainers:
  - name: Steven
    email: steven.crespo@rancher.com
