url: https://kubernetes-charts.banzaicloud.com/charts/logging-operator-3.9.0.tgz
packageVersion: 02
releaseCandidateVersion: 03
additionalCharts:
  - workingDir: charts-crd
    crdOptions:
      templateDirectory: crd-template
      crdDirectory: templates
      addCRDValidationToMainChart: true
