apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sriov-network-config-daemon
  namespace: {{ .Release.Namespace }}
