apiVersion: citrix.com/v1alpha1
kind: HTTPRoute
metadata:
   name: header-routing 
spec:
  hostname:
  - host1.com
  rules:       
  - name: rulename 
    match:
    - headers:
      - headerName:
          contains: mobile 
    action:
      backend:
        kube:
          service: mobilesvc
          port: 80

