apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    istiocoredns:
      enabled: {{ .Values.istiocoredns.enabled }}
    prometheus:
      enabled: false
    grafana:
      enabled: false
    kiali:
      enabled: false
    tracing:
      enabled: false
  components:
    base:
      enabled: {{ .Values.base.enabled }}
    cni:
      enabled: {{ .Values.cni.enabled }}
    egressGateways:
    - enabled: {{ .Values.egressGateways.enabled }}
      name: istio-egressgateway
    ingressGateways:
    - enabled: {{ .Values.ingressGateways.enabled }}
      name: istio-ingressgateway
      k8s:
        service:
          ports:
          - name: status-port
            port: 15021
            targetPort: 15021
          - name: http2
            port: 80
            targetPort: 8080
            nodePort: 31380
          - name: https
            port: 443
            targetPort: 8443
            nodePort: 31390
          - name: tcp
            port: 31400
            targetPort: 31400
            nodePort: 31400
          - name: tls
            port: 15443
            targetPort: 15443
    istiodRemote:
      enabled: {{ .Values.istiodRemote.enabled }}
    pilot:
      enabled: {{ .Values.pilot.enabled }}
    policy:
      enabled: {{ .Values.policy.enabled }}
    telemetry:
      enabled: {{ .Values.telemetry.enabled }}
  hub: {{ .Values.systemDefaultRegistry | default "docker.io" }}
  profile: default
  tag: {{ .Values.tag }}
  revision: {{ .Values.revision }}
  meshConfig:
    enablePrometheusMerge: {{ .Values.meshConfig.enablePrometheusMerge }}
  values:
    gateways:
      istio-egressgateway:
        name: istio-egressgateway
        type: {{ .Values.egressGateways.type }}
      istio-ingressgateway:
        name: istio-ingressgateway
        type: {{ .Values.ingressGateways.type }}
    global:
      istioNamespace: {{ template "istio.namespace" . }}
      proxy:
        image: {{ template "system_default_registry" . }}{{ .Values.global.proxy.repository }}:{{ .Values.global.proxy.tag }}
      proxy_init:
        image: {{ template "system_default_registry" . }}{{ .Values.global.proxy_init.repository}}:{{ .Values.global.proxy_init.tag }}
    istiocoredns:
      coreDNSImage: {{ template "system_default_registry" . }}{{ .Values.istiocoredns.image.repository }}
      coreDNSPluginImage: {{ template "system_default_registry" . }}{{ .Values.istiocoredns.pluginImage.repository }}:{{ .Values.istiocoredns.pluginImage.tag }}
      coreDNSTag: {{ .Values.istiocoredns.image.tag }}
    mixer:
      {{- if .Values.policy.enabled }}
      policy:
        image: {{ template "system_default_registry" . }}{{ .Values.policy.repository}}:{{ .Values.policy.tag }}
      {{- end }}
      {{- if .Values.telemetry.enabled }}
      telemetry:
        image: {{ template "system_default_registry" . }}{{ .Values.telemetry.repository}}:{{ .Values.telemetry.tag }}
      {{- end }}
    {{- if .Values.pilot.enabled }}
    pilot:
      image: {{ template "system_default_registry" . }}{{ .Values.pilot.repository}}:{{ .Values.pilot.tag }}
    {{- end }}
    {{- if .Values.cni.enabled }}
    cni:
      image: {{ template "system_default_registry" . }}{{ .Values.cni.repository }}:{{ .Values.cni.tag }}
    {{- end }}
