apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "logging-operator.labels" . | indent 4 }}
spec:
  controlNamespace: {{ .Release.Namespace }}
  fluentbit:
    image:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.fluentbit.repository }}
      tag: {{ .Values.images.fluentbit.tag }}
    tolerations:
      {{ toYaml .Values.fluentbit_tolerations | nindent 6 }}
  fluentd:
    image:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.fluentd.repository }}
      tag: {{ .Values.images.fluentd.tag }}
    configReloaderImage:
      repository: {{ template "system_default_registry" . }}{{ .Values.images.config_reloader.repository }}
      tag: {{ .Values.images.config_reloader.tag }}
    disablePvc: {{ .Values.disablePvc }}
