apiVersion: v2
name: local-path-provisioner
description: Use HostPath for persistent local storage with Kubernetes
keywords:
  - storage
  - hostpath
type: application
version: 0.1.0
appVersion: "v0.0.18"
kubeVersion: ">=1.12.0-r0"
icon: file://../local-path.png
